"""Core module exports for ObtainHub."""

from obtainhub.core.config import Config, ConfigManager, get_config, get_config_manager
from obtainhub.core.state import InstalledApp, ManifestEntry, StateManager, get_state_manager
from obtainhub.core.logger import ObtainHubLogger, LogLevel, get_logger, setup_logging
from obtainhub.core.exceptions import (
    ObtainHubError,
    ConfigError,
    ConfigNotFoundError,
    ConfigValidationError,
    NetworkError,
    DownloadError,
    InstallerError,
    InstallerNotFoundError,
    InstallerExecutionError,
    GitHubAPIError,
    RateLimitError,
    NotFoundError,
    AuthenticationError,
    ValidationError,
    ManifestError,
    ManifestNotFoundError,
    ManifestParseError,
    SelfUpdateError,
    SelfUpdateCheckFailedError,
    SelfUpdateFailedError,
    SelfUpdateSkippedError,
    StateError,
    StateNotFoundError,
    StateCorruptedError,
    CLIError,
    CLIArgumentError,
    CLICommandError,
)
from obtainhub.core.self_updater import SelfUpdater, ReleaseInfo

__all__ = [
    "Config",
    "ConfigManager",
    "get_config",
    "get_config_manager",
    "InstalledApp",
    "ManifestEntry",
    "StateManager",
    "get_state_manager",
    "ObtainHubLogger",
    "LogLevel",
    "get_logger",
    "setup_logging",
    "ObtainHubError",
    "ConfigError",
    "ConfigNotFoundError",
    "ConfigValidationError",
    "NetworkError",
    "NetworkTimeoutError",
    "NetworkConnectionError",
    "HTTPError",
    "HTTPNotFoundError",
    "HTTPForbiddenError",
    "HTTPTooManyRequestsError",
    "HTTPServerError",
    "ManifestError",
    "ManifestNotFoundError",
    "ManifestParseError",
    "ManifestValidationError",
    "ManifestNotFoundLocallyError",
    "ManifestSourceError",
    "ManifestSourceNotFoundError",
    "ManifestSourceUnavailableError",
    "InstallerError",
    "InstallerNotFoundError",
    "InstallerExecutionError",
    "InstallerVerificationError",
    "InstallerUnsupportedTypeError",
    "DownloadError",
    "DownloadCancelledError",
    "DownloadVerificationError",
    "DownloadIncompleteError",
    "ChecksumError",
    "ChecksumMismatchError",
    "UnsupportedHashAlgorithmError",
    "VerificationError",
    "SignatureVerificationError",
    "CertificateError",
    "SelfUpdateError",
    "SelfUpdateNotNeededError",
    "SelfUpdateFailedError",
    "CLIError",
    "CLIArgumentError",
    "CLICommandError",
    "SelfUpdater",
    "ReleaseInfo",
]