"""Core module exports for ObtainHub."""

from obtainhub.core.config import (
    Config,
    ConfigManager,
    ManifestSource,
    get_config,
    get_config_manager,
)
from obtainhub.core.state import (
    InstalledApp,
    ManifestEntry,
    StateManager,
    get_state_manager,
)
from obtainhub.core.logger import (
    LogLevel,
    LogRecord,
    JSONFormatter,
    ConsoleFormatter,
    StructuredLogger,
    setup_logging,
    get_logger,
    get_default_logger,
)
from obtainhub.core.self_updater import (
    ReleaseInfo,
    SelfUpdater,
    check_and_update,
)
from obtainhub.core.exceptions import (
    ObtainHubError,
    ConfigError,
    ConfigNotFoundError,
    ConfigValidationError,
    NetworkError,
    DownloadError,
    InstallerError,
    InstallerNotFoundError,
    InstallerExecutionError,
    SelfUpdateError,
    SelfUpdateNotNeededError,
    StateError,
    StateNotFoundError,
    StateValidationError,
    CLIError,
    CLIArgumentError,
)
from obtainhub.core.asset_matcher import (
    InstallerType,
    Architecture,
    AssetInfo,
    DownloadDecision,
    detect_architecture,
    detect_installer_type,
    parse_asset,
    filter_windows_x64_installers,
    find_best_installer,
    find_zip_assets,
    get_system_architecture,
    is_windows_x64,
    decide_download_action,
)

__all__ = [
    # Config
    "Config",
    "ConfigManager",
    "ManifestSource",
    "get_config",
    "get_config_manager",
    # State
    "InstalledApp",
    "ManifestEntry",
    "StateManager",
    "get_state_manager",
    # Logger
    "LogLevel",
    "LogRecord",
    "JSONFormatter",
    "ConsoleFormatter",
    "StructuredLogger",
    "setup_logging",
    "get_logger",
    "get_default_logger",
    # Self Updater
    "ReleaseInfo",
    "SelfUpdater",
    "check_and_update",
    # Exceptions
    "ObtainHubError",
    "ConfigError",
    "ConfigNotFoundError",
    "ConfigValidationError",
    "NetworkError",
    "DownloadError",
    "InstallerError",
    "InstallerNotFoundError",
    "InstallerExecutionError",
    "SelfUpdateError",
    "SelfUpdateNotNeededError",
    "StateError",
    "StateNotFoundError",
    "StateValidationError",
    "CLIError",
    "CLIArgumentError",
    # Asset Matcher
    "InstallerType",
    "Architecture",
    "AssetInfo",
    "DownloadDecision",
    "detect_architecture",
    "detect_installer_type",
    "parse_asset",
    "filter_windows_x64_installers",
    "find_best_installer",
    "find_zip_assets",
    "get_system_architecture",
    "is_windows_x64",
    "decide_download_action",
]