# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Determine if we're building for signing (disable UPX)
import os
IS_SIGNED_BUILD = os.environ.get("OBTAINHUB_SIGNED_BUILD", "0") == "1"

a = Analysis(
    ['obtainhub/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('obtainhub/core/config.py', 'obtainhub/core'),
        ('obtainhub/core/state.py', 'obtainhub/core'),
        ('obtainhub/core/logger.py', 'obtainhub/core'),
        ('obtainhub/core/exceptions.py', 'obtainhub/core'),
        ('obtainhub/core/github_client.py', 'obtainhub/core'),
        ('obtainhub/core/asset_matcher.py', 'obtainhub/core'),
        ('obtainhub/core/downloader.py', 'obtainhub/core'),
        ('obtainhub/core/installer.py', 'obtainhub/core'),
        ('obtainhub/core/self_updater.py', 'obtainhub/core'),
        ('obtainhub/core/self_uninstall.py', 'obtainhub/core'),
        ('obtainhub/utils/helpers.py', 'obtainhub/utils'),
        ('obtainhub/utils/backup.py', 'obtainhub/utils'),
        ('obtainhub/ports/__init__.py', 'obtainhub/ports'),
        ('obtainhub/adapters/__init__.py', 'obtainhub/adapters'),
        ('obtainhub/plugins/__init__.py', 'obtainhub/plugins'),
        ('obtainhub/plugins/sandbox.py', 'obtainhub/plugins'),
        ('obtainhub/plugins/sandbox_runner.py', 'obtainhub/plugins'),
    ],
    hiddenimports=[
        'obtainhub.core.config',
        'obtainhub.core.state',
        'obtainhub.core.logger',
        'obtainhub.core.exceptions',
        'obtainhub.core.github_client',
        'obtainhub.core.asset_matcher',
        'obtainhub.core.downloader',
        'obtainhub.core.installer',
        'obtainhub.core.self_updater',
        'obtainhub.core.self_uninstall',
        'obtainhub.utils.helpers',
        'obtainhub.utils.backup',
        'obtainhub.ports',
        'obtainhub.adapters.github_adapter',
        'obtainhub.adapters.json_state_store',
        'obtainhub.plugins',
        'obtainhub.plugins.example',
        'obtainhub.plugins.sandbox',
        'obtainhub.plugins.sandbox_runner',
        'requests',
        'urllib3',
        'textual',
        'rich',
        'keyring',
        'keyrings.alt',
        'json',
        'pathlib',
        'dataclasses',
        'typing',
        'datetime',
        'threading',
        'tempfile',
        'subprocess',
        'importlib.metadata',
        'argparse',
        'signal',
        'shutil',
        'logging',
        're',
        'hashlib',
        'base64',
        'stat',
        'platform',
        'ctypes',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'PIL',
        'cv2',
        'test',
        'tests',
        'pytest',
        'unittest',
        'doctest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# Build as onedir for binary hardening (ASLR/DEP/CFG work properly)
# onefile disables these security features
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ohub',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=not IS_SIGNED_BUILD,  # Disable UPX for signed builds
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch='x86_64',
    codesign_identity=None,
    entitlements_file=None,
    icon='',
    onefile=False,  # onedir mode for security hardening
)
